# Change these first
owner: AOT-Technologies
repo: forms-flow-upptime

sites:
  - name: Sandbox Web
    url: https://trynow-formsflow-web.aot-technologies.com/tenant/formsflowai
  - name: Sandbox Keycloak
    url: https://forms-flow-idm-prod.aot-technologies.com/auth/realms/multitenant/.well-known/openid-configuration
  - name: Sandbox API
    url: https://forms-flow-api-prod.aot-technologies.com/
  - name: Sandbox Admin API
    url: https://forms-flow-admin-prod.aot-technologies.com/api/v1/swagger.json
  - name: Sandbox Forms
    url: https://forms-flow-forms-prod.aot-technologies.com/
  - name: Sandbox BPM
    url: https://forms-flow-bpm-prod.aot-technologies.com/camunda
    
assignees: # Users to assign downtime issues (optional)
  - formsflow-product-team
   

status-website:
  baseUrl: /forms-flow-upptime
  logoUrl: https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/master/forms-flow-web/src/assets/styles/formsflow.ai_icon.svg
  name: formsflow.ai
  introTitle: "formsflow.ai status"
  introMessage: "[**formsflow.ai**](https://formsflow.ai/) is a Free, Open-Source, Low Code Development Platform for rapidly building powerful business applications. [**formsflow.ai**](https://formsflow.ai/) combines leading Open-Source applications including [form.io](https://form.io) forms, Camunda’s workflow engine, Keycloak’s security, and Redash’s data analytics into a seamless, integrated platform."

  navbar:
    - title: Status
      href: /forms-flow-upptime
    - title: GitHub
      href: https://github.com/AOT-Technologies/forms-flow-upptime/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
