# Change these first
owner: AOT-Technologies
repo: forms-flow-ai

sites:
  - name: Sandbox Web
    url: https://app3.aot-technologies.com/tenant/formsflow
  - name: Sandbox Keycloak
    url: https://iam3.aot-technologies.com/auth/realms/multitenant-app3/.well-known/openid-configuration
#   - name: Sandbox API
#     url: https://iam3.aot-technologies.com/auth/realms/multitenant-app3/.well-known/openid-configuration
   
   

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: app3.aot-technologies.com
  baseUrl: /forms-flow-upptime
  logoUrl: https://raw.githubusercontent.com/AOT-Technologies/forms-flow-ai/master/forms-flow-web/src/assets/styles/formsflow.ai_icon.svg
  name: formsflow.ai
  introTitle: "formsflow.ai status"
  introMessage: [**formsflow.ai**](https://formsflow.ai/) is a Free, Open-Source, Low Code Development Platform for rapidly building powerful business applications. [**formsflow.ai**](https://formsflow.ai/) combines leading Open-Source applications including [form.io](https://form.io) forms, Camunda’s workflow engine, Keycloak’s security, and Redash’s data analytics into a seamless, integrated platform.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/AOT-Technologies/forms-flow-ai/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
