name: Google chat notification

on:
  issues:
    types: [ opened, reopened ]

jobs:
  Google_Chat_Notification:
    runs-on: ubuntu-latest
    steps:
    - name: Echo
      run: |
        echo "${{ github.event }}"
        echo "${{github.event.issue}}" 
        echo "${{github.event.issue.label}}" 
        echo "${{github.event.issue.label.name}}"
        echo "${{github.event.issue.url}}"
        
    - name: Google Chat Notification
      # if: ${{ github.event.issue.label.name == 'status' }}
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: "Incident - https://github.com/AOT-Technologies/forms-flow-upptime/issues/6/${{ github.event.issue.number }}"
        url: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}
        status: failure
